# 初心者のための TensorFlow 2.0 入門

https://www.tensorflow.org/tutorials/quickstart/beginner

In [17]:
import tensorflow as tf

In [18]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255., X_test / 255.

In [19]:
model = tf.keras.models.Sequential([
	tf.keras.layers.Flatten(input_shape=(28, 28)),
	tf.keras.layers.Dense(128, activation='relu'),
	tf.keras.layers.Dropout(0.2),
	tf.keras.layers.Dense(10)
])

In [20]:
predictions = model(X_train[:1]).numpy()
predictions

array([[-0.63865614, -0.84598535,  0.30154634,  0.30027914,  0.47198415,
         0.6066361 ,  0.24268834, -0.595736  , -0.7515372 , -0.4865299 ]],
      dtype=float32)

In [21]:
tf.nn.softmax(predictions).numpy()

array([[0.05275285, 0.04287498, 0.13507365, 0.1349026 , 0.16017357,
        0.18326074, 0.12735292, 0.0550663 , 0.04712184, 0.06142052]],
      dtype=float32)

In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [23]:
loss_fn(y_train[:1], predictions).numpy()

1.6968453

In [24]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [25]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2994 - accuracy: 0.9123
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1473 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1116 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0885 - accuracy: 0.9720
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0765 - accuracy: 0.9761


In [27]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0716 - accuracy: 0.9776


[0.07160965353250504, 0.9775999784469604]

In [28]:
probability_model = tf.keras.Sequential([
	model,
	tf.keras.layers.Softmax(),
])

In [29]:
probability_model.predict(X_test[:3])

array([[8.2270013e-08, 6.4263452e-09, 3.2719354e-06, 2.2479687e-04,
        1.2598665e-09, 3.9285075e-07, 1.3575896e-13, 9.9977106e-01,
        1.0909654e-07, 3.6026125e-07],
       [1.6341813e-09, 6.4192910e-04, 9.9935216e-01, 4.9196256e-06,
        1.0070529e-13, 4.1725627e-07, 1.7672208e-07, 1.3934483e-12,
        4.5024865e-07, 8.3953943e-13],
       [1.7986615e-07, 9.9822265e-01, 6.6434346e-05, 9.4997276e-06,
        3.2717362e-05, 1.3713556e-05, 5.4868451e-05, 1.4817570e-03,
        1.1752539e-04, 5.8502820e-07]], dtype=float32)